name: collql
description: Collection Query Language, for document match and search.
version: 1.0.0
repository: https://github.com/jessicamrbr/CollQL

environment:
  sdk: ^3.7.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
dependencies:
  json_schema: ^5.2.1
  rfc_6901: ^0.2.0
  uuid: ^4.5.1
